from __future__ import annotations

from .call import _agentic_json_call
from .context import _FTS_TOKEN_RE, _fts_query_from_substring, _neighbors_limited, _seed_context
from .dispatch import (
    _clamp_float,
    _clamp_int,
    _dispatch_tool,
    _tool_error,
    _tool_ok,
    _validate_tool_result,
)
from .public import analyze_agentic, evolve_agentic, fix_agentic
from .schema import _extract_refusal, _normalize_responses_json_schema, _parse_model_json
from .self_check import _run_self_check
from .tools import (
    _build_call_index,
    _build_route_patterns,
    _call_matches_any_pattern,
    _candidate_keys_from_path,
    _candidate_keys_from_static_prefix,
    _compute_api_coverage,
    _compute_prefix_map,
    _join,
    _load_ts_typedefs_by_name,
    _method_norm,
    _normalize_http_path,
    _pattern_matches_any_call,
    _prefix_key_from_segments,
    _prefix_norm,
    _read_text_under_root,
    _static_prefix_segs_from_tokens,
    _tool_api_coverage_summary,
    _tool_compare_api_contract,
    _tool_definitions,
    _tool_get_contract,
    _tool_get_file,
    _tool_get_file_lines,
    _tool_get_neighbors,
    _tool_get_node,
    _tool_get_symbol,
    _tool_get_tree_outline,
    _tool_impact_route_change,
    _tool_project_summary,
    _tool_route_usages,
    _tool_search_api_calls,
    _tool_search_paths,
    _tool_search_routes,
    _tool_search_semantic,
    _tool_search_symbols,
    _tool_search_tests,
    _tool_search_text,
    _tool_suggest_api_fix,
    _tool_suggest_contract_fix,
    _tool_suggest_endpoint_location,
    _tool_suggest_frontend_client,
    _tool_unmatched_calls,
    _tool_unmatched_routes,
    _ts_type_to_py_literal,
)
from .types import AgenticMeta

__all__ = [
    "AgenticMeta",
    "analyze_agentic",
    "evolve_agentic",
    "fix_agentic",
    "_FTS_TOKEN_RE",
    "_agentic_json_call",
    "_build_call_index",
    "_build_route_patterns",
    "_call_matches_any_pattern",
    "_candidate_keys_from_path",
    "_candidate_keys_from_static_prefix",
    "_clamp_float",
    "_clamp_int",
    "_compute_api_coverage",
    "_compute_prefix_map",
    "_dispatch_tool",
    "_extract_refusal",
    "_fts_query_from_substring",
    "_join",
    "_load_ts_typedefs_by_name",
    "_method_norm",
    "_neighbors_limited",
    "_normalize_http_path",
    "_normalize_responses_json_schema",
    "_parse_model_json",
    "_pattern_matches_any_call",
    "_prefix_key_from_segments",
    "_prefix_norm",
    "_read_text_under_root",
    "_run_self_check",
    "_seed_context",
    "_static_prefix_segs_from_tokens",
    "_tool_api_coverage_summary",
    "_tool_compare_api_contract",
    "_tool_definitions",
    "_tool_error",
    "_tool_get_contract",
    "_tool_get_file",
    "_tool_get_file_lines",
    "_tool_get_neighbors",
    "_tool_get_node",
    "_tool_get_symbol",
    "_tool_get_tree_outline",
    "_tool_impact_route_change",
    "_tool_ok",
    "_tool_project_summary",
    "_tool_route_usages",
    "_tool_search_api_calls",
    "_tool_search_paths",
    "_tool_search_routes",
    "_tool_search_semantic",
    "_tool_search_symbols",
    "_tool_search_tests",
    "_tool_search_text",
    "_tool_suggest_api_fix",
    "_tool_suggest_contract_fix",
    "_tool_suggest_endpoint_location",
    "_tool_suggest_frontend_client",
    "_tool_unmatched_calls",
    "_tool_unmatched_routes",
    "_ts_type_to_py_literal",
    "_validate_tool_result",
]
